server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db-account:5432/accountdb
    username: user
    password: pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info
